export {
  AUTHORIZED_COMPETITIONS,
  AUTHORIZED_COMPETITIONS_BY_KEY,
  AUTHORIZED_COMPETITIONS_BY_PROVIDER_ID,
  AUTHORIZED_COMPETITION_AVAILABILITY_STATUSES,
  AUTHORIZED_COMPETITION_COUNTRIES,
  AUTHORIZED_COMPETITION_KEYS,
  AUTHORIZED_COMPETITION_REGIONS,
  AUTHORIZED_COMPETITION_TYPES,
  COMPETITION_AVAILABILITY_STATUSES,
  COMPETITION_TYPES,
  assertAuthorizedCompetitionKey,
  getAuthorizedCompetitionByKey,
  isAuthorizedCompetitionKey
} from './competitionCatalog.js'
