export const DEFAULT_SPORTS_API_PROVIDER = 'api-football'
export const DEFAULT_SPORTS_API_BASE_URL = 'https://v3.football.api-sports.io'
export const DEFAULT_SPORTS_API_MIN_INTERVAL_MS = 7000
export const DEFAULT_SPORTS_API_RETRY_AFTER_FALLBACK_MS = 65000
export const DEFAULT_SPORTS_API_SOFT_LIMIT_PERCENT = 80
export const DEFAULT_SPORTS_SYNC_LOOKAHEAD_HOURS = 24
export const DEFAULT_SPORTS_SYNC_MAX_FIXTURES = 40
export const DEFAULT_SPORTS_SYNC_HISTORY_MAX_PAGES_PER_RUN = 2
